name: py38_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - pip
  - pip:
    - ipykernel
    - numpy>=1.17.2,<1.24.0
    - numba<=0.55.2
    - pandas>=0.25.1,<2.0.0
    - pyarrow>=10.0.1
    - fastparquet>=2022.12.0
    - scikit-learn>=0.22.1,<1.1 # See PR 1429 about upper bound
    - scipy>=1.4.1
    - semver~=2.13.0
    - ml-wrappers
    - ipywidgets>=8.0.7 
    - jupyterlab-widgets>=3.0.8 
    - widgetsnbextension>=4.0.8
    - keyring>=4.1.1
    - keyrings.alt
    - azure-ai-ml
    - azure-cli
    - azureml-core
    - azure-ai-contentsafety>=1.0.0b1
    - pytest
    - flask>=2.2.3  


